<?php
if(isset($_GET['login']) && $_GET['login'] == "try" && isset($_POST['email']) && isset($_POST['password']))
{
    $reponse = $bdd->prepare('SELECT * FROM users WHERE users.email = :email AND users.password = :password LIMIT 0,1');
    //secure input data
    $user_email = htmlspecialchars($_POST['email']);
    //encrypt password
    $user_password = sha1($_POST['password']);

    //Execute query with prepared data
    $reponse->execute(array('email' => $user_email, 'password' => $user_password));

    while($donnees = $reponse->fetch())
    {
        //create session
        session_start();

        $_SESSION['ID'] = $donnees['ID'];
        $_SESSION['pseudo'] = $donnees['pseudo'];
        $_SESSION['email'] = $donnees['email'];
        $_SESSION['password'] = $donnees['password'];
        $_SESSION['corpo_id'] = $donnees['corpo_id'];
    }

    $reponse->closeCursor();

    /* Redirection vers une page différente du même dossier */
    $host  = $_SERVER['HTTP_HOST'];
    $uri   = rtrim(dirname($_SERVER['PHP_SELF']), '/\\');
    $page_cible = 'index.phtml';
    header("Location: http://$host$uri/$page_cible");
    exit;
}
?>
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>INSPINIA | Login</title>

    <link href="../css/bootstrap.min.css" rel="stylesheet">
    <link href="../font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="../css/animate.css" rel="stylesheet">
    <link href="../css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">IN+</h1>

            </div>
            <h3>Welcome to IN+</h3>
            <p>Perfectly designed and precisely prepared admin theme with over 50 pages with extra new web app views.
                <!--Continually expanded and constantly improved Inspinia Admin Them (IN+)-->
            </p>
            <p>Login in. To see it in action.</p>
            <form class="m-t" role="form" action="index.phtml?login=try" method="POST">
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Username" required="" name="email">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password" required="" name="password">
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

                <a href="#"><small>Forgot password?</small></a>
                <p class="text-muted text-center"><small>Do not have an account?</small></p>
                <a class="btn btn-sm btn-white btn-block" href="../register.html">Create an account</a>
            </form>
            <p class="m-t"> <small>Inspinia we app framework base on Bootstrap 3 &copy; 2014</small> </p>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="../js/jquery-2.1.1.js"></script>
    <script src="../js/bootstrap.min.js"></script>

</body>

</html>
