<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Ozelit SaaS CMS | Login</title>

    <link href="resources/css/bootstrap.min.css" rel="stylesheet">
    <link href="resources/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="resources/css/animate.css" rel="stylesheet">
    <link href="resources/css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">Oz+</h1>

            </div>
            <h3>Bienvenue sur la solution <br>Ozelit SaaS CMS</h3>
            <p>La solution de gestion de contenus simple et professionnelle.</p>
            <form class="m-t" role="form" action="index.php?page=login&login=try" method="POST" novalidate="novalidate">
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Email" name="email">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Mot de passe" name="password">
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

                <a href="#"><small>Mot de passe oublié ?</small></a>
                <p class="text-muted text-center"><small>Pas encore utilisateur du service ?</small></p>
                <a class="btn btn-sm btn-white btn-block" href="../register.html">Découvrir la solution Oz+</a>
            </form>
            <p class="m-t"> <small>Tous droits réservés &copy; Ozelit</small> </p>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="resources/js/jquery-2.1.1.js"></script>
    <script src="resources/js/bootstrap.min.js"></script>

    <!-- jQuery validate -->
    <script src="resources/js/plugins/validate/jquery.validate.min.js"></script>

</body>

</html>
